# version: '3.1'

services:

  node-server:
    build: ./node-server
    restart: always
    environment:
      PORT: 8080
    ports:
      - "7071:8080"

  python-server:
    build: ./python-server
    restart: always
    environment:
      PORT: 8081
    ports:
      - "7072:8081"

  spring-server:
    build: ./spring_server
    restart: always
    environment:
      PORT: 8080
    ports:
      - "7073:8080"

  go-server:
    build: ./go-server
    restart: always
    environment:
      PORT: 8080
    ports:
      - "7074:8080" 

  dotnet-server:
    build: ./csharp-server
    restart: always
    environment:
      PORT: 8080
    ports:
      - "7075:8080"
  
  php-server:
    build: ./php-server
    restart: always
    environment:
      PORT: 80
    ports:
      - "7076:80"

  ruby-server:
    build: ./ruby-server
    restart: always
    environment:
      PORT: 4567
    ports:
      - "7077:4567"

  rust-server:
    build: ./rust-server
    restart: always
    environment:
      PORT: 8082
    ports:
      - "7078:8082"
  
  kotlin-server:
    build: ./kotlin-server
    restart: always
    environment:
      PORT: 8083
    ports:
      - "7079:8083"

  cpp-server:
    build: ./cpp-server
    restart: always
    environment:
      PORT: 8084
    ports:
      - "7080:8084"

  loadbalancer:
    image: nginx:alpine
    restart: always
    ports:
      - 9000:80
    depends_on:
      - node-server
      - python-server
      - spring-server
      - go-server
      - dotnet-server
      - php-server
      - ruby-server
      - rust-server
      - kotlin-server
      - cpp-server
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf