upstream backend {
    server  node-server:3000;
    server python-server:5000;
    server spring-server:8080;
}

server{
	listen 80;
	server_name _;

    location / {
        proxy_pass http://backend;
    }
}