upstream backend {
    server php-server:80;
    server go-server:8080;
    server cpp-server:8084;
    server ruby-server:4567;
    server rust-server:8082;
    server node-server:8080;
    server python-server:8081;
    server spring-server:8080;
    server dotnet-server:8080;
    server kotlin-server:8083;
}

server{
	listen 80;
	server_name _;

    location / {
        proxy_pass http://backend;
        proxy_set_header Host $http_host;
    }
}